### ISSUE TITLE
multiple captcha and remote resources

### ISSUE THREAD

**Issue by drzraf** [DanSnow/vue-recaptcha#104]
I'm trying to use `vue-recaptcha` inside a (bootstrap) modal. I've one modal for each "item"... and I may show various items on the page at a time.

The issue is that *each* and *every* time `vue-recaptcha` template is used, a bunch of remote resources are loaded like `recaptcha__en.js`, `styles__ltr.css` + a lot of subresources like fonts, ...

I don't want all of these being massively reloaded each time one `vue-recaptcha` is referenced.
I tried to make my modals `lazy` : this is a workaround which avoid hanging my browser when showing 50 items, but recaptcha resources are still loaded and reloaded each time the modal is closed then reopened.

Is there something doable about this?

**Comment by DanSnow** [comment]
Google reCAPTCHA will create an iframe for each recaptcha.
So those resources will be loaded when the iframe created.
It's recaptcha's behavior but not `vue-recaptcha`.
Maybe a better way is reuse a same modal if it's allowed.
And use the `reset` method to reset the recaptcha if needed.
