### ISSUE TITLE
Response of useChallengeV3

### ISSUE THREAD

**Issue by srenevey** [DanSnow/vue-recaptcha#1050]
When using `useChallengeV3`, what does the response contain? It looks like a hash of something but I can't figure out how to use it to validate the request.

**Comment by DanSnow** [comment]
You'll need to call an API from reCAPTCHA with the response token to get the result https://developers.google.com/recaptcha/docs/verify#api_request

**Comment by srenevey** [comment]
Ah that makes sense. Thanks!
