### ISSUE TITLE
dist/vue-recaptcha.es.js : not webpack-compatible

### ISSUE THREAD

**Issue by drzraf** [DanSnow/vue-recaptcha#106]
When bundling vue-recaptcha using webpack, it fail to render the template:
```
Failed to mount component: template or render function not defined. found in
---> <VueRecaptcha>
```

The issue does not arise when using direct/raw ES6 imports.

I also found that adding such an alias to webpack.config.babel.js did the trick (vue-recaptcha.es.js is used by default):
```
resolve: {
    alias: {
      'vue-recaptcha$': 'vue-recaptcha/dist/vue-recaptcha.js'
    }
}
```

I would thus say that there is an issue with `dist/vue-recaptcha.es.js`

**Comment by DanSnow** [comment]
Thanks for reporting issue. However I cannot reproduce this issue.
Can you please provide a code snippet to show how you import vue-recaptcha ?
Or output of `webpack --verbose` .

**Comment by drzraf** [comment]
```js
// entry.js:
import VueRecaptcha from 'vue-recaptcha';
window['VueRecaptcha'] = VueRecaptcha;
```

```js
// captcha-post.js:
export default {
   // ...
   components: { "vue-recaptcha": VueRecaptcha },
   // ...
}
```

**Comment by DanSnow** [comment]
I still cannot reproduce this issue.
Can you please provide your webpack config and output of `webpack --verbose`?
