### ISSUE TITLE
3.0.0-alpha.4 - Error: useRecaptcha() is called without provider.  

### ISSUE THREAD

**Issue by web2wire** [DanSnow/vue-recaptcha#1108]
Hi,

I'm experimenting with version 3.0.0-alpha.4 of this module in a NuxtJS 3.4.1 environment but getting the above error. This is what the console is outputting. I get pretty much the same issue whether I put the useRecaptchaProvider call in the specific form, the page or app.vue. It's not clear from the docs where it's really supposed to go. One of the errors suggests that "you may forget to `use` vue-recaptcha plugin" however as I'm using Nuxt and have registered the vue-recaptcha/nuxt module in nuxt.config.ts I am assuming that should have taken care of that step.

![image](https://user-images.githubusercontent.com/383834/233356922-b30333da-8d73-4cf9-a1db-4ec65b450d47.png)

Am I doing something wrong somewhere or is this a possible bug?

**Comment by suraj740** [comment]
@web2wire, did you get any workaround?
 I am also facing the same issue.

**Comment by web2wire** [comment]
No, I've not found any way to get past this yet.

**Comment by DanSnow** [comment]
Hey @web2wire @suraj740, do you have a reproducible example?

**Comment by mishabachkur** [comment]
I have a similar problem that is critical for me

**Comment by web2wire** [comment]
I think this demo shows the problem, https://stackblitz.com/edit/nuxt-starter-zjauks?file=components/Demo.vue. There might be extra bits in there that aren't necessary but it's pretty basic and the generated error is the same as what I'm seeing though it's possible I've missed something out from my real application I guess.

**Comment by DanSnow** [comment]
Thanks @web2wire, I understood the issue.

@mishabachkur @suraj740 Here is a quick workaround. Please remove the `import {...} from 'vue-recaptcha'` in your Nuxt app and rely on auto import.

The issue is because Nuxt auto import and `import {} from 'vue-recaptcha` will actually import different files, and `vue-recaptcha` uses a symbol as the injection key. Which causes the plugin context can't be found. 

I'll update to use a string key to prevent this case.

**Comment by mishabachkur** [comment]
@DanSnow I got it working. Thank you for your help

**Comment by mishabachkur** [comment]
@DanSnow I have a warning - "reCAPTCHA couldn't find user-provided function: __vueRecaptchaLoaded". It's ok? 
I init useRecaptchaProvider() in the default layout

UPD. If I call reCAPTCHA in vue-final-modal, I get this warning. If I init to Nuxt pages, it is not present

**Comment by DanSnow** [comment]
@mishabachkur That's ok.

- If vue-recaptcha is loaded before reCAPTCHA's script => vue-recaptcha will register a callback for reCAPTCHA to notify it's loaded => nothing happen
- If vue-recaptcha is loaded after reCAPTCHA's script => vue-recaptcha will check `grecaptcha` on `window` to get the reCAPTCHA API => reCAPTCHA will warn about callback not found
