### ISSUE TITLE
Do not render recaptcha

### ISSUE THREAD

**Issue by mishabachkur** [DanSnow/vue-recaptcha#1118]
Browser: Google Chrome. 
vue-recaptcha version: **^3.0.0-alpha.4.**
Nuxt version: **^3.2.3**

My steps to reproduce:
1. Add to nuxt config
```typescript
defineNuxtConfig({
  modules: ['vue-recaptcha/nuxt'],
  runtimeConfig: {
    public: {
      recaptcha: {
        v2SiteKey: process.env.RECAPTCHA_SITEKEY
      }
    }
  }
})
``` 
2. Add to my page
```typescript
const form = ref({
  'g-recaptcha-response': ''
})
<div class="form-group">
   <RecaptchaCheckbox v-model="form['g-recaptcha-response']" />
</div>
``` 

Result
![image](https://user-images.githubusercontent.com/3975266/234066996-81495a5c-9945-4317-a6d4-d524e619785c.png)

**Comment by mishabachkur** [comment]
@DanSnow Can you help me? Thank you

**Comment by DanSnow** [comment]
Did you call the `useRecaptchaProvider`? https://dansnow.github.io/vue-recaptcha/guide#provide-recaptcha-script

**Comment by mishabachkur** [comment]
@DanSnow Is this also necessary to do for Nuxt?

**Comment by mishabachkur** [comment]
@DanSnow I added it like this
```typescript
<script setup>
import { useRecaptchaProvider } from 'vue-recaptcha'

useRecaptchaProvider()

const form = ref({
  'g-recaptcha-response': ''
})

</script>

<template>
  <div class="form-group">
    <RecaptchaCheckbox v-model="form['g-recaptcha-response']" />
  </div>
</template>
``` 
But I received this error

![image](https://user-images.githubusercontent.com/3975266/234352023-47565079-976f-46cf-ab6b-33c1890b3816.png)

**Comment by mishabachkur** [comment]
[It's working now](https://github.com/DanSnow/vue-recaptcha/issues/1108)
