### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by pSchaub** [DanSnow/vue-recaptcha#113]
The peer dependency version for vue is not correct.

I get the following warning message:
```
warning "vue-recaptcha@1.1.0" has unmet peer dependency "vue@^2.0.0".
```

This is my package.json:
```
"vue": "^2.5.13"
```

Any vue 2.x version should be allowed as correct peer dependency.

**Comment by DanSnow** [comment]
Thanks for reporting issue.
I'll take a look at this weekend.

**Comment by DanSnow** [comment]
Which package manager are you using?
