### ISSUE TITLE
Is it possible to bind recaptcha component to v-model?

### ISSUE THREAD

**Issue by Tarasovych** [DanSnow/vue-recaptcha#114]
I want to validate if recaptcha passed before AJAX request. Is it possible to bind component to v-model?
Like `<vue-recaptcha v-model="recaptcha" type="checkbox" size="compact" sitekey=""></vue-recaptcha>`

**Comment by DanSnow** [comment]
Sorry, currently it's impossible.
Because recaptcha also has expired state, I haven't found a better way to represent it.
So now I'm only using event.
If you have any idea please let me know.
