### ISSUE TITLE
TSX/JSX Example

### ISSUE THREAD

**Issue by Stoom** [DanSnow/vue-recaptcha#115]
Hello all,

I've been trying to get this to work in a tsx file.  I cannot seem to find the right place to put the google javascript `script` tag and have it load.  If I add it to the index.html then it loads before vue and give me an error it cannot find the `onload` callback.  If I put it in the tsx then webpack cannot load correctly.

Are there any examples or advice on how to get this to work?

Cheers,

James

**Comment by Stoom** [comment]
The following is my  solutions using a mixin

```typescript
import { Component as Mixin, Vue } from 'vue-property-decorator';

@Mixin({
  mounted: () => {
    const script = document.createElement('script');
    script.src = 'https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit';
    script.async = true;
    script.defer = true;

    document.body.appendChild(script);
  },
})
export default class GoogleRecaptchaMixin extends Vue { }
```

**Comment by Stoom** [comment]
This may be a good mixin to include in the package so that there is less setup to get using the  plugin.

**Comment by DanSnow** [comment]
Sorry for late reply.

I think it could be a great.
However, due to private issue, I doesn't have much time to work on this package recently.
I'll keep this issue open.

**Comment by texdc** [comment]
@Stoom One problem with that solution is that every time the component is mounted, the script will be added to the DOM.  It'd be better to check for it beforehand and only render the script tag if necessary.
