### ISSUE TITLE
ERROR  Unknown file extension ".vue" for node_modules/vue-recaptcha/dist/components/ChallengeV2.vue

### ISSUE THREAD

**Issue by GuillaumeDgr** [DanSnow/vue-recaptcha#1201]
Hi,

When trying to build for production (yarn generate), the following message appears : 'ERROR  Unknown file extension ".vue" for node_modules/vue-recaptcha/dist/components/ChallengeV2.vue'

I'm using nuxt3 and "vue-recaptcha": "^3.0.0-alpha.5".

Any idea to solve this pls ?

Many thanks

**Comment by yzoz** [comment]
I have the same

**Comment by ItsMeRomian** [comment]
If you're using Nuxt3, you can add 
```js
  build: {
    transpile: ["vue-recaptcha"],
  },
```
To your `nuxt.config.ts`. This fixed it for me.

**Comment by dmitrisi4** [comment]
On stack Laravel InertiaJS Vue 3 Vite
I added format: 'cjs' in my vite.config,js
    ssr: {
        noExternal: ['@inertiajs/server'],
        format: 'cjs'
    },
    Helped solve a similar problem

**Comment by GuillaumeDgr** [comment]
@ItsMeRomian solution is working well, thanks a lot!

**Comment by DanSnow** [comment]
Close as duplicate with #1186
