### ISSUE TITLE
Getting "TypeError: window.grecaptcha.render is not a function" errors

### ISSUE THREAD

**Issue by moltar** [DanSnow/vue-recaptcha#123]
Getting a lot of errors:

> TypeError: window.grecaptcha.render is not a function

I think this is due to the external script not being loaded yet?

Also, I am using SSR, so could be because of that?

**Comment by angelika94** [comment]
same issue

**Comment by SamanthaAdrichem** [comment]
@ralls his change fixes it for me too. Please notify me if it's available through npm. Made a dummy fork for now.

**Comment by DanSnow** [comment]
@moltar Thanks for reporting the issue.

New version is available on the npm.
ping @angelika94 @ralls @SamanthaAdrichem @maximivanov
