### ISSUE TITLE
useRecaptcha() is called without a provider

### ISSUE THREAD

**Issue by 7FULL** [DanSnow/vue-recaptcha#1240]
### Description

Ive tried everything to get the vue recaptcha working but It keeps throwing the same error.

```
client.ts:18 [vite] connecting...
client.ts:150 [vite] connected.
runtime-core.esm-bundler.js:41 [Vue warn]: injection "usehead" not found. 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
runtime-core.esm-bundler.js:41 [Vue warn]: injection "Symbol(vue-recaptcha-context)" not found. 
  at <Checkbox> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
runtime-core.esm-bundler.js:41 [Vue warn]: [vue-recaptcha]: You may forget to `use` vue-recaptcha plugin 
  at <Checkbox> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
runtime-core.esm-bundler.js:41 [Vue warn]: Unhandled error during execution of setup function 
  at <Checkbox> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:41
context.mjs?v=0f4b048e:8 Uncaught Error: useRecaptcha() is called without provider.
    at useRecaptchaContext (context.mjs?v=0f4b048e:8:11)
    at useAssertV2SiteKey (context.mjs?v=0f4b048e:17:15)
    at useChallengeV2 (challenge-v2.mjs?v=0f4b048e:12:19)
    at useComponentV2 (component-v2.mjs?v=0f4b048e:5:83)
    at setup (Checkbox.vue:46:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
```
    
    
Even in a new proyect and doing the exact thing as in the doc.

### Minimal Reproducible Example

App.vue

```vue
<script setup>
import { Checkbox, useRecaptchaProvider } from 'vue-recaptcha';
import { RouterView } from 'vue-router'

useRecaptchaProvider();
</script>

<template>
  <div id="app">
    <Checkbox />
    <router-view />
  </div>
</template>


<style scoped>
</style>
```

Main.js

```ts
import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'
import { VueRecaptchaPlugin } from 'vue-recaptcha'

const app = createApp(App)

app.use(VueRecaptchaPlugin, {
  v2SiteKey: '6Lc9z9EmAAAAAEMtU3tyFP2wGTJf2slUMaDL_P6t',
  v3SiteKey: '6Lc099EmAAAAAI_Ra6YRJ35X0FjthvtuXyH0X8E9',
})

app.use(createPinia())
app.use(router)

app.mount('#app')
 ```
 
 Packague.json
 
 ```json
{
  "name": "pruebacaptcha",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@unhead/vue": "^1.1.30",
    "pinia": "^2.1.3",
    "vue": "^3.3.4",
    "vue-recaptcha": "^3.0.0-alpha.2",
    "vue-router": "^4.2.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "vite": "^4.3.9"
  }
}
```

### System info

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 15.93 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3       
    vite: ^4.3.9 => 4.4.2
    vue-recaptcha: ^3.0.0-alpha.2 => 3.0.0-alpha.2

By the way OS is not correct wtf

![Captura de pantalla 2023-07-10 165613](https://github.com/DanSnow/vue-recaptcha/assets/95145682/97ac3d37-dab8-40e5-a6b1-eeacdb5ff745)

**Comment by DanSnow** [comment]
Maybe duplicate with #1108. Could you try upgrading to the latest version? (`3.0.0-alpha.6`)

**Comment by 7FULL** [comment]
> Maybe duplicate with #1108. Could you try upgrading to the latest version? (`3.0.0-alpha.6`)

Bruh, that solve it. Thank you so much. Btw how can I make it required in a form?

**Comment by DanSnow** [comment]
You can try integrating vee-validate or another form-validation package. http://dansnow.github.io/vue-recaptcha/integration/vee-validation

**Comment by 7FULL** [comment]
> You can try integrating vee-validate or another form-validation package. http://dansnow.github.io/vue-recaptcha/integration/vee-validation

Ok thanks!!!
