### ISSUE TITLE
Nuxt3: Invisible recaptcha visible (dev & prod)

### ISSUE THREAD

**Issue by GuillaumeDgr** [DanSnow/vue-recaptcha#1259]
### Description

Using Nuxt3, Tailwind and vite, invisible recaptcha is still visible in dev (yarn dev) or in prod after build (yarn generate).

### Minimal Reproducible Example

Please find below my configuration and integration of vue-recaptcha:

- package.json

```json
"devDependencies": {
   ...,
   "nuxt": "^3.4.2",
   ...,
},
"dependencies": {
    ...,
    "vue-recaptcha": "^3.0.0-alpha.5"
    ...,
}
```

- nuxt.config.js

```js
modules: [
    ...
    "vue-recaptcha/nuxt",
    ...
],
runtimeConfig: {
    public: {
      recaptcha: {
        v2SiteKey: "*****",
        v3SiteKey: "*****", // I'm using only V2 but I try to add/delete (according to some SO comments) this line without no effect
      },
    },
 },
build: {
    transpile: ["vue-recaptcha"], // Solution provided in #1186 to avoir build errors
 },
```

- page.vue

```vue
<template>
...
 <div ref="root" class="hidden invisible" style="visibility: hidden" /> // I have tried to add these styles without any effects
 ...
 </template>
 
 <script setup lang="ts">
 import { useRecaptchaProvider } from "vue-recaptcha";
 import { useChallengeV2 } from "vue-recaptcha";

 useRecaptchaProvider();
 
 const { root, widgetID, execute, onVerify, onExpired, onError, reset } =
 useChallengeV2({
  options: {
    size: "invisible",
  },
 });
 
 onVerify(async (response) => {
    ...
    POST request
    ...
 });
 
 onExpired(() => {
    ...
     reset();
 });
```

- Node version:
 v19.1.0

### System info

------------------------------
- Operating System: Darwin
- Node Version:     v19.1.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, runtimeConfig, plugins, build, googleFonts, strapi, i18n, colorMode, gtag, image, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @nuxtjs/google-fonts@3.0.1, @nuxtjs/strapi@1.9.3, @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/color-mode@3.2.0, @nuxtjs/robots@3.0.0, @nuxt/image@1.0.0-rc.1, nuxt-icon@0.4.1, nuxt-gtag@0.5.7, nuxt-jsonld@2.0.8, vue-recaptcha/nuxt
- Build Modules:    -
------------------------------

**Comment by DanSnow** [comment]
I tested the example you provided, and I did not encounter any issue with the invisible reCAPTCHA being visible. If you are referring to the badge, you can refer to this link on how to hide it.

https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

**Comment by GuillaumeDgr** [comment]
Hi, you're right, sorry for that, it's a mistake on my part, I confused the recaptcha and the badge...

**Comment by DanSnow** [comment]
No worries. I added a note on the document for this. https://dansnow.github.io/vue-recaptcha/components/challenge-v2#about-the-visible-badge-for-invisible-recaptcha
