### ISSUE TITLE
error in mounted hook: window.grecaptcha.render is not a function

### ISSUE THREAD

**Issue by jadvillafania** [DanSnow/vue-recaptcha#126]
I'm getting inconsistent result. Sometimes it works, sometimes I get error. 

It seems that the vue-recaptcha is trying to create the component even when the google recaptcha is not yet recognized.

I placed the tag `<script src="https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit" async defer></script> ` one line above my app.js and followed the usage guide.

**Comment by Halo-Josh** [comment]
I'm getting this too

**Comment by DanSnow** [comment]
Which version are you using?
Doesn't this issue duplicate with #123 and should be resolved with #124?

**Comment by jadvillafania** [comment]
I think its duplicate.
