### ISSUE TITLE
how to implement in nuxt3 ?

### ISSUE THREAD

**Issue by nabeel-nexttier** [DanSnow/vue-recaptcha#1283]

**Comment by DanSnow** [comment]
Please refer to the documentation for Nuxt at https://dansnow.github.io/vue-recaptcha/guide/nuxt and the get started guide at https://dansnow.github.io/vue-recaptcha/guide.

Additionally, the documentation is built on top of Nuxt 3, and you can check the configuration at https://github.com/DanSnow/vue-recaptcha/blob/v3/docs/nuxt.config.ts and the demo code at https://github.com/DanSnow/vue-recaptcha/blob/v3/docs/components/content/CheckboxDemo.vue.

**Comment by nabeel-nexttier** [comment]
it just doesn't show , if i use it as a plugin it gives following error Unknown file extension ".vue" for node_modules\vue-recaptcha\dist\components\ChallengeV2.vue
