### ISSUE TITLE
Documentation is not enough

### ISSUE THREAD

**Issue by PhmNgocNghia** [DanSnow/vue-recaptcha#137]
type (optional)
The type of reCAPTCHA
size (optional)
The size of reCAPTCHA

I don't see any document about those parameter

**Comment by DanSnow** [comment]
Sorry for late reply. I just came back from a vacation.

Since this properties is same as reCAPTCHA config.
I just assume user will know how to use reCAPTCHA.
But we can resolve this by copy and paste these parameter's description from reCAPTCHA document simply.

**Comment by fnick851** [comment]
@DanSnow Could you point me to where is the reCAPTCHA documentation for "type"?
