### ISSUE TITLE
emit successfully loaded event

### ISSUE THREAD

**Issue by lkloon123** [DanSnow/vue-recaptcha#139]
hi, first of all thanks for this great plugin.

i would like to ask would u mind to add emitting an event after recaptcha has been successfully added?

Thanks,
Have a nice day.

**Comment by DanSnow** [comment]
Do you mean emit an event after reCAPTCHA rendered?
Can you provide a use case?

Because reCAPTCHA doesn't provide an api to achieve this.
I'll need some workaround to detect that it has been rendered.
But if you can explain what you are trying to do, maybe we can find another way.

**Comment by lkloon123** [comment]
hi, thanks for the reply.

im trying to do execute() on mount, but recaptcha is not rendered at that time, 
so i was thinking to run execute() when recaptcha has been rendered.

**Comment by DanSnow** [comment]
But I think that reCAPTCHA need user interactive to determine if user is a human.
So mostly people will run `execute` when submit button click or similar.
