### ISSUE TITLE
Execute method not firing in FireFox and Edge but does in Chrome

### ISSUE THREAD

**Issue by MovehMakeh** [DanSnow/vue-recaptcha#148]
Hello, 
I am trying to run this:
`this.$refs.recaptcha.execute();`
after my inputs are validated
submit: function () {
```
                    this.status = "submitting";
                    this.validateBeforeSubmit();
                    if(window.valid == true){
                        this.$refs.recaptcha.execute();
                    }
                },
```
But once it gets to that line, it does nothing from there in FireFox and Edge, but does in Chrome.

Any ideas?

**Comment by DanSnow** [comment]
Can you please provide a [codepen](httsp://codepen.io) (or jsfiddle) that can reproduce this?

**Comment by MovehMakeh** [comment]
That, or could I provide you a link to my site?

**Comment by MovehMakeh** [comment]
Suddenly it worked today, thank you for the quick response before! :)
