### ISSUE TITLE
vue-recaptcha renders a div on body every render.

### ISSUE THREAD

**Issue by helixion** [DanSnow/vue-recaptcha#149]
This video pretty much displays what I'm talking about.

https://youtu.be/NNgj98rsBTE

I'm using vue-recaptcha as added guard on form submissions, of which I have many on my site. I have a recaptcha for signing up, and when you change your profile settings I have one there also. Whenever the vue-recaptcha element is rendered it attached a div to the body. keep-alive is not an option because the component that vue-recaptcha is attached has a conditional which will "unrender" it once logged it. Same goes for the profile page since if you transition from one route to the next and back again it will re-render vue-recaptcha and insert the div.

Also having multiple recaptchas on different pages and transitioning to them seems to effect performance.

**Comment by helixion** [comment]
Nope, just using the "i am not a robot" solution. The way I have it setup is that if they pass the recaptcha check and fill the required fields, it will enable the submit button.

**Comment by pakiam** [comment]
Hi, I`m using invisible recaptcha on my index page and recaptcha challenge rendering every time in DOM, then I visit it. Any help?
