### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by Frzurita** [DanSnow/vue-recaptcha#155]
my code is the following:

```
          <vue-recaptcha
            ref="recaptcha"
            @verify="createCard"
            size="invisible"
            :sitekey="siteKey"/>
```

and then, in the mounted hook I execute this code:

```
    if (!window.recaptcha) {
      let script = document.createElement('script')
      script.type = 'text/javascript'
      script.src = 'https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit'
      document.body.appendChild(script)
    }
```

When I go to see the stats in google recaptcha web page, I get the following error:
<img width="504" alt="screen shot 2018-07-16 at 09 27 49" src="https://user-images.githubusercontent.com/11997189/42747085-1d800bf4-88db-11e8-8ce2-d4a8907da023.png">

Do you know what could be happening?

**Comment by DanSnow** [comment]
Sorry, I never get this error before.
https://stackoverflow.com/questions/49592772/google-recaptcha-v2-javascript-we-detected-that-your-site-is-not-verifying-recap
