### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by eWings-agency** [DanSnow/vue-recaptcha#1570]
### Description

Broken link of documentation.

### Minimal Reproducible Example

Broken link of documentation.

### System info

Broken link of documentation.

**Comment by DanSnow** [comment]
Thanks for letting me know. Fixed in https://github.com/DanSnow/vue-recaptcha/commit/d66d1f77b229c80c3d0dcde7fd3930428df7d1f8

**Comment by Jesus82** [comment]
@DanSnow docs are down again :(

**Comment by DanSnow** [comment]
@Jesus82 sorry for the inconvenience. It should be fixed.
