### ISSUE TITLE
Example has wrong variable name

### ISSUE THREAD

**Issue by pjcunningham** [DanSnow/vue-recaptcha#160]
`index.js`
```
resetRecaptcha () {
      this.$refs.recaptcha.reset() // Direct call reset method
    }
```

```
resetRecaptcha () {
      this.$refs.invisibleRecaptcha.reset() // Direct call reset method
    }
```

**Comment by DanSnow** [comment]
Thanks for reporting the issue.

But there are 3 recaptcha in the example and I just only call the `reset` on the first one.

**Comment by pjcunningham** [comment]
My apologies - Vue newbie!!! Didn't read through the example code sufficiently.
