### ISSUE TITLE
responsive catpcha content

### ISSUE THREAD

**Issue by VCodepp** [DanSnow/vue-recaptcha#164]
How to responsive capcha content ?

**Comment by DanSnow** [comment]
You can use `size="compact`' to get a smaller recaptcha. [doc](https://developers.google.com/recaptcha/docs/display#render_param)
But if you want to make recaptcha's content really responsive, that is seem impossible.
Since the content is an iframe which provided by Google recaptcha.

**Comment by VCodepp** [comment]
I guess it does not change. Thank you.
