### ISSUE TITLE
uncaught (in promise) request timed out

### ISSUE THREAD

**Issue by sivakavi** [DanSnow/vue-recaptcha#191]
Hi,
After clicking recaptcha checkbox, it is not woking, it shows error in console.
Error : Uncaught (in promise) Request timed out.

**Comment by DanSnow** [comment]
Can you please check your network connection?
reCAPTCHA need to connect to Google's server.

**Comment by josueaqp92** [comment]
i think that it is the same problem https://productforums.google.com/forum/#!topic/websearch/RTYnWdp4oi0 , it happens sometimes it invisible size

**Comment by michaelprankl99** [comment]
Why does this error occur even if `load-recaptcha-script="false"` and in my network traffic I don't see an request to the google api?
