### ISSUE TITLE
[question] what is the defer here for?

### ISSUE THREAD

**Issue by adamchenwei** [DanSnow/vue-recaptcha#196]
https://github.com/DanSnow/vue-recaptcha/blob/c02720c2c40519276d8dffb03f857ba29402d40b/src/defer.js#L1

I am not clear how defer interaction with wrapper work as? Seems it just popped out of nowhere to start notify and stuff... I failed to see the key connection between defer and the rest of the code base start from the wrapper. 

Would it be possible to help me understand it by elaborating a bit? Thank you so much @DanSnow 
Thank you for writting this awesome work 👍

**Comment by DanSnow** [comment]
`vue-recaptcha` have to way to detect recaptcha api loaded. The first one is just check `window.hasOwnProperty('grecaptcha')`

https://github.com/DanSnow/vue-recaptcha/blob/c02720c2c40519276d8dffb03f857ba29402d40b/src/recaptcha-wrapper.js#L39

Second one is using the recpatcha api's url parameter. With the `onload` param, recaptcha will call the function on `window` when loaded completely

https://github.com/DanSnow/vue-recaptcha/blob/c02720c2c40519276d8dffb03f857ba29402d40b/src/recaptcha-wrapper.js#L59

Both of them call the notify to make the `render` function start to render.

Actually I used the native Promise before. It's much simpler:

```js
function defer () {
  const deferred = {}
  deferred.promise = new Promise(resolve => {
    deferred.resolve = resolve
  })
  return deferred
}
```

When the `resolve` called, the Promise will be resolved. And the callback that register on Promise will be executed. Also after Promise enter the resolved state, it wont transform into other state. If somebody call the `promise.then` on a resolved promise, the callback will also be execute:

```js
const promise = Promise.resolve()
promise.then(() => {
  console.log('This will be execute')
})
promise.then(() => {
  console.log('Also this one')
})
```

I think this is a great way to implement the notify. When I'm sure that recaptcha has loaded, I just resolve the promise. Then all the callback on the promise will be executed.

However promise isn't available under IE. I just make a simpler version by myself. That is the `defer`.

**Comment by adamchenwei** [comment]
sounds good! will look into it a bit! close it for now. thank you for the detailed reply! good learning!

**Comment by Humoyun** [comment]
good trick for IE
