### ISSUE TITLE
Question - Vue-Racaptcha future

### ISSUE THREAD

**Issue by DM2489** [DanSnow/vue-recaptcha#198]
Hi,

Google Recaptcha 3 is now live. This significantly reduces the complexity of handling Recaptcha, essentially reducing it to a single function call.

More info - https://developers.google.com/recaptcha/docs/v3

How does this affect the future of this plugin?

**Comment by DanSnow** [comment]
Currently I have no plan about this. But I think maybe we can do something like:

```html
<form>
  <vue-recaptcha-v3 v-model="recaptchaToken" @click="submitForm">
    <button type="submit">Submit</button>
  </vue-recaptcha-v3>
</form>
```
And `vue-recaptcha` can use capture event to get `submit` or `click` event of its child, then set the `recaptchaToken` and emit the `click` to let user can have the token and continue process the submit.

Or maybe change to directive like:

```js
<form>
  <button v-recaptcha:click="submitForm">Submit</button>
</form>
```

`click` is the event name. Then you can get the recaptcha token in `submitForm` as second argument (first one is the `$event`).

**Comment by DanSnow** [comment]
Yeah, so I think we just need a way to trigger `execute` and return the token to user.

**Comment by callumflack** [comment]
Does this mean that currently this module only supports Recaptcha v2? 

Because it is not stated at all in the README. I think it should be clearly stated.

**Comment by DanSnow** [comment]
ok, I can add it to readme

**Comment by callumflack** [comment]
Thanks. I'm grateful you've made this :)
