### ISSUE TITLE
"key" is a reserved attribute

### ISSUE THREAD

**Issue by Anheru** [DanSnow/vue-recaptcha#20]
> [Vue warn]:"key" is a reserved attribute and cannot be used as component prop.

> [Vue warn]: Missing required prop: "key" (found in component <vue-recaptcha>)

**Comment by DanSnow** [comment]
Thanks. I'll fix it as soon as possible.

**Comment by DanSnow** [comment]
I have renamed key to sitekey, and published [v0.2.0](https://github.com/DanSnow/vue-recaptcha/releases/tag/v0.2.0).
