### ISSUE TITLE
onVerify not init

### ISSUE THREAD

**Issue by iiiusky** [DanSnow/vue-recaptcha#204]
onVerify func not exec...

**Comment by DanSnow** [comment]
Please provide a snippet to reproduce this.

**Comment by iiiusky** [comment]
```
<template>
  <div class="login-page">
    <div class="layer bg" id="login"></div>
    <div class="layer flex-center">
      <div class="logo-group">
        <img src="./image/logo.png" alt="logo">
      </div>
      <div class="form-group">
        <el-card>
          <el-form ref="loginForm" label-position="top" :rules="rules" :model="formLogin" size="default">
            <el-form-item  prop="username">
              <el-input type="text" v-model="formLogin.username" placeholder="username">
                <i slot="prepend" class="fa fa-user-circle-o"></i>
              </el-input>
            </el-form-item>
            <el-form-item prop="password">
              <el-input type="password" v-model="formLogin.password" placeholder="password">
                <i slot="prepend" class="fa fa-keyboard-o"></i>
              </el-input>
            </el-form-item>
              <vue-recaptcha
            ref="invisibleRecaptcha"
            @verify="onVerify"
            @expired="onExpired"
            size="invisible"
            :sitekey="sitekey">
          </vue-recaptcha>

    <el-button size="default" @click="submit" type="primary" class="button-login">Login</el-button>
          </el-form>
        </el-card>
      </div>
    </div>
  </div>
</template>

<script>
/* eslint-disable */
require('particles.js')
import config from './config/default'
import { mapActions } from 'vuex'
import VueRecaptcha from 'vue-recaptcha';
export default {
  data () {
    return {
      sitekey: '6LfHiX0UAAAAAH12S2q4il2P5Db7yLqVerEQ6PKH',
      formLogin: {
        username: '',
        password: '',
        token:''
      },
      // 校验
      rules: {
        username: [
          { required: true, message: 'please input username', trigger: 'blur' }
        ],
        password: [
          { required: true, message: 'please input password, trigger: 'blur' }
        ],
      }
    }
  },
  mounted () {

    particlesJS('login', config);
    this.$refs.invisibleRecaptcha.execute()
  },
  components: {
    'vue-recaptcha': VueRecaptcha

  },
  beforeDestroy () {
    // thanks https://github.com/d2-projects/d2-admin/issues/65
    // ref https://github.com/VincentGarreau/particles.js/issues/63
    if (pJSDom && pJSDom.length > 0) {
      pJSDom[0].pJS.fn.vendors.destroypJS()
      pJSDom = []
    }
  },
  methods: {
    onVerify: function (response) {
      console.log('Verify: ' + response)
    },
    onExpired: function () {
      console.log('Expired')
    },
    resetRecaptcha () {
      this.$refs.recaptcha.reset() // Direct call reset method
    },

    submit () {
      
      this.$refs.loginForm.validate((valid) => {
        if (valid && this.formLogin.token != '') {
          this.login({
            vm: this,
            username: this.formLogin.username,
            password: this.formLogin.password,
            token:this.formLogin.token,
          })
        } else {
          this.$message.error('error')
        }
      })
    }
  }
}
</script>

<style lang="scss">
@import './style.scss';
</style>

```


The **onVerify** method has no execution record

**Comment by DanSnow** [comment]
It's seem that you are using invisible recaptcha. It need to trigger manually by calling `execute` on `this.$refs.invisibleRecaptcha.execute()`.

**Comment by iiiusky** [comment]
Why do I add execute in the mounted without leaving？

**Comment by iiiusky** [comment]
I added execute to the mounted, and then saw that this.$widgetId is undefined. How to solve this?

![](http://ww1.sinaimg.cn/large/90e682d1ly1fxss7a6i5bj20y40dwgoh.jpg)

**Comment by DanSnow** [comment]
You can't add it at `mounted`. You need to add it at `submit` handler.
Or consider to use normal recaptcha.

**Comment by iiiusky** [comment]
Now I found another problem, `this.$refs.recaptcha.reset()` is not working, because there is no reset method, `$refs` does not have this `recaptcha` method, I am verifying it every time. Then refresh the verification code by `window.grecaptcha.reset();`

**Comment by iiiusky** [comment]
When I use invisible mode, I can see the returned value in the elements in the page, but I just can't get it.

![](http://ww1.sinaimg.cn/large/90e682d1ly1fxss7a6i5bj20y40dwgoh.jpg)

**Comment by DanSnow** [comment]
> Now I found another problem, `this.$refs.recaptcha.reset()` is not working, because there is no reset method, `$refs` does not have this `recaptcha` method

The `recpatcha` is the ref key which need to configure by yourself. You can use:

```html
<vue-recaptcha ref="recpatcha"></vue-recaptcha>
```

Then you can access `this.$refs.recaptcha`.

> I am verifying it every time. Then refresh the verification code by `window.grecaptcha.reset();`

I don't get it. Why you need to verify and refresh it?

**Comment by DanSnow** [comment]
If you configure it successfully, vue-recpatcha will emit the `verify` event with the recaptcha's response.

**Comment by Pezhvak** [comment]
> > Now I found another problem, `this.$refs.recaptcha.reset()` is not working, because there is no reset method, `$refs` does not have this `recaptcha` method
> 
> The `recpatcha` is the ref key which need to configure by yourself. You can use:
> 
> ```
> <vue-recaptcha ref="recpatcha"></vue-recaptcha>
> ```
> 
> Then you can access `this.$refs.recaptcha`.
> 
> > I am verifying it every time. Then refresh the verification code by `window.grecaptcha.reset();`
> 
> I don't get it. Why you need to verify and refresh it?

watch out for the typo in ref="recaptcha", it should be ref="recaptcha"
