### ISSUE TITLE
[Bug / Feature] Disabled state can't be applied to the button

### ISSUE THREAD

**Issue by adamchenwei** [DanSnow/vue-recaptcha#208]
reproduce
git clone https://github.com/adamchenwei/vuejs-disabled-button-toggle-playground
git checkout bug/vue-recaptcha-wrapped-button-cannot-be-disabled
yarn && yarn serve

click on `A Button With Recaptcha` button, see even it wired up with state to toggle disabled state, yet, it does not, but the button with `A Button` will see got disabled!

Any idea if its a bug of the library @DanSnow

**Comment by DanSnow** [comment]
OK, it's seem like google recaptcha will try to modify the button's state. So it's not a bug of this library.
And also I don't have any idea for solving this currently.

**Comment by adamchenwei** [comment]
is there way we can make the vue-recaptcha to display an alternative dom when some sort of custom `isDisabled` param get triggered while, not impacting the loading of the recaptcha logic? like, maybe abstract the class name out into its own? I am not yet 100% sure how this whole idea can work... or not? I guess you would have a better idea lead further? or its not possible... for some reason, if you could elaborate?
