### ISSUE TITLE
access the widget id in a callback after its set?

### ISSUE THREAD

**Issue by adamchenwei** [DanSnow/vue-recaptcha#209]
Is there way to do that? even the hacky way? @DanSnow 
I need it to properly reset recaptcha with grecaptcha.reset(widgetId)

**Comment by adamchenwei** [comment]
@DanSnow this served my purpose. but if its not good to do, let me know, or close if its good on your end as well

mounted() {
    console.warn('mounted____', this.$refs.recaptcha.$widgetId);
  }

**Comment by DanSnow** [comment]
Although I haven't document it. But I don't think I'll change this in the future. Maybe is fine.

**Comment by adamchenwei** [comment]
cool
