### ISSUE TITLE
Renders a div on body

### ISSUE THREAD

**Issue by pakiam** [DanSnow/vue-recaptcha#215]
Hi, I`m using invisible recaptcha on my index page and recaptcha challenge rendering every time in DOM, then I visit it. Any help?
![screenshot_15](https://user-images.githubusercontent.com/11723092/50517061-5f92d380-0abf-11e9-89c9-a44e09d4cda3.png)

**Comment by pakiam** [comment]
@DanSnow Im using invisible recaptcha. And how '.g-recaptcha-bubble-arrow'`s parentElement connected with element inside body?

**Comment by collyrooms** [comment]
> @DanSnow Im using invisible recaptcha. And how '.g-recaptcha-bubble-arrow'`s parentElement connected with element inside body?

I'm also facing this issue with  invisible recaptcha. The element injected into the dom doesnt have any handle to target.
@pakiam  did you find a fix for this?
