### ISSUE TITLE
Return recaptcha token on execute

### ISSUE THREAD

**Issue by basselAhmed** [DanSnow/vue-recaptcha#237]
My case is that I am trying to use an invisible recaptcha which will be invoked and used in the same click event.
It'd be nice if ```this.$refs.recaptcha.execute()``` returns the token on success and error on failure.
We can use promises or callbacks, both are fine but I prefer promises.
if you agree with me on this, I might be able to help with a PR.

**Comment by DanSnow** [comment]
That sounds great. Feel free to open a PR. Can we provide callback by default and only provide promises when available? I think maybe somebody is still using this package in IE that doesn't have promise support.
