### ISSUE TITLE
[Discussion] Dialog Covering Up Invisible Recaptcha Popup

### ISSUE THREAD

**Issue by adamchenwei** [DanSnow/vue-recaptcha#251]
I already filed a bug to recaptcha itself here https://github.com/google/recaptcha/issues/318. But since I reproduced it with vue-recaptcha, thought maybe there is some insight, @DanSnow you could share? I am sure likely its not a vue-recaptcha bug, but I would love to know if any implementation of this library can help work around it ... somehow?

Play it here https://codepen.io/adamchenwei/pen/agbPYJ
Info here https://stackoverflow.com/questions/56544906/html-dialog-element-is-covering-up-invisible-recaptcha-challenge-popup-how-to-f

Thanks!

**Comment by DanSnow** [comment]
I have try these method:

- z-index
- `display: none` on `::backdrop`

But neither of them work.
