### ISSUE TITLE
NPM Package Is Outdated

### ISSUE THREAD

**Issue by animalchinster** [DanSnow/vue-recaptcha#254]
I installed the package via npm and could not get the `loadRecaptchaScript` prop to work. I then looked into `node_modules/vue-recaptcha/dist/vue-recaptcha.js` and saw that the component only has these props:
```
    props: {
      sitekey: {
        type: String,
        required: true
      },
      theme: {
        type: String
      },
      badge: {
        type: String
      },
      type: {
        type: String
      },
      size: {
        type: String
      },
      tabindex: {
        type: String
      }
    },
```
It seems like the npm package is out of sync with the master branch. Going to implement my own auto load from the parent component as a workaround until this is fixed.

**Comment by animalchinster** [comment]
Also, the versioning seems off to me, as npm states 1.1.1 as the latest version, however the master branch that includes the newer props is also 1.1.1.

**Comment by DanSnow** [comment]
I have publish v1.2.0 and it should available on NPM now

**Comment by animalchinster** [comment]
Awesome, thanks for the quick response!
