### ISSUE TITLE
ReCaptcha init

### ISSUE THREAD

**Issue by klivak** [DanSnow/vue-recaptcha#266]
Hi, can I load ReCaptcha only when I open modal or do other actions? I have form registration in the modal window, so, to make a better performance I would like to load and initialize it only after modal is open. Can I do that?

**Comment by DanSnow** [comment]
Just wrap your model content with `v-if`:

```vue
<div :v-if="open">
  <!-- other content -->
  <vue-recaptcha></vue-recaptcha>
</div>
```

**Comment by klivak** [comment]
Yeap, thanx. 
Also, it would be better if add "prop" ->   :load-recaptcha-script="true"
