### ISSUE TITLE
allowing to add data-callback attribute onto the checkbox dom?

### ISSUE THREAD

**Issue by adamchenwei** [DanSnow/vue-recaptcha#267]
trying to wire up js function when a user click on the checkbox itself. seems this is the only way by add `data-callback` attribute onto the captcha dom.

Think its possible to add into vue-recaptcha?

https://stackoverflow.com/questions/28674946/how-to-check-in-js-that-user-has-checked-the-checkbox-in-google-recaptcha

**Comment by DanSnow** [comment]
The functionality of  `data-callback` is mapped to `verify` event in `vue-recaptcha`. Please use the `verify` event.
