### ISSUE TITLE
recaptcha language

### ISSUE THREAD

**Issue by fardinj** [DanSnow/vue-recaptcha#269]
i want change google recaptcha language for my web site
i couldnt find any answer to how do that

**Comment by DanSnow** [comment]
Sorry for late reply. You need to config it by recaptcha api's url param https://developers.google.com/recaptcha/docs/display#js_param

**Comment by cyborg-z** [comment]
Should be possible to set while using loadRecaptchaScript

**Comment by DanSnow** [comment]
@cyborg-z Do you have any idea about how it should work? Also a PR is always welcome.

**Comment by cyborg-z** [comment]
@DanSnow Sorry for the "it should work", I'll take a look in the upcoming days for a possible PR

**Comment by DanSnow** [comment]
Great news. It's already support in v1.3.0
