### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by ChxGuillaume** [DanSnow/vue-recaptcha#285]
Getting `Uncaught Error: Missing required parameters: sitekey` even when given in the balise.

(My case was after a page reload)

**Comment by DanSnow** [comment]
Can you please provide a reproducing step and your code?

**Comment by ChxGuillaume** [comment]
I just literally followed this : https://itnext.io/how-to-use-google-recaptcha-with-vuejs-7756244400da

**Comment by DanSnow** [comment]
The example in the tutorial should work. Please provide your code. I think maybe you are missing something.

**Comment by ChxGuillaume** [comment]
For now i've that :
`
<vue-recaptcha @verify="onCaptchaVerified" @expired="onCaptchaExpired" size="invisible"
               sitekey="6LftwLkUAAAAAHUJXvZY-gZ5e20WQOvlwyBM9A-E" :loadRecaptchaScript="true" ref="recaptcha">
  <button type="submit" class="btn btn-primary g-recaptcha">Envoyer</button>
</vue-recaptcha>
`

and

`
submit(e) {
    e.preventDefault();
    this.$refs.recaptcha.execute();
},
onCaptchaVerified(recaptchaToken) {
    console.log(recaptchaToken);
},
onCaptchaExpired: function () {
    this.$refs.recaptcha.reset();
},
`

with a `@submit="submit"` on the form tag

**Comment by DanSnow** [comment]
Please don't wrap your button with `vue-recaptcha`
