### ISSUE TITLE
[Vue warn]: Missing required prop: "sitekey"

### ISSUE THREAD

**Issue by jeffersonagostinho** [DanSnow/vue-recaptcha#288]
HELP!

I am experiencing this error when adding recaptcha _[Vue warn]: Missing required prop: "sitekey"_

CODE

`<vue-recaptcha ref="recaptcha" :siteKey="siteKey"
    :loadRecaptchaScript="true">
</vue-recaptcha>`

Thanks

**Comment by DanSnow** [comment]
Please change `:siteKey` to `:sitekey`. It's case sensitive.
