### ISSUE TITLE
The vue-recaptcha component is not rendered when its loaded in the dom before the google recaptcha api

### ISSUE THREAD

**Issue by ristedavcevski** [DanSnow/vue-recaptcha#313]
The documentation says that the vue-recaptcha component will be rendered when the google recaptcha api script is loaded by setting the flag **onload=vueRecaptchaApiLoaded**, but this does not work.

It only works when the vue-recaptcha component is hidden by a v-if (example: inside a Modal). The google recaptcha api script is already loaded when i open the Modal and the component has no problems with the rendering there.

**Comment by DanSnow** [comment]
Could you please provide a reproducing steps or a codepen?

**Comment by ristedavcevski** [comment]
I did some investigating about this issue and could not reproduce it a Codepen. Seems like the issue happens only when i use **<vue-recaptcha>** on two different forms on the same page.

It is enough just to import the VueRecaptcha component inside of two different single file components (hence why i can not do this in a simple Codepen) and the recaptcha does not render. If i remove one of the imports, everything works correctly in the other component.

It is a really weird issue, i will try to provide some sort of dummy app in a sandbox webpack environemnt.
