### ISSUE TITLE
How to get the callback function for loading completion

### ISSUE THREAD

**Issue by 158008001** [DanSnow/vue-recaptcha#318]
I want to make a mask to prevent clicks unless the js is loaded.

But the callback function is occupied by the plugin and cannot complete this action.

My users often complain that button clicks have no effect.

This is the result of my research:

`src="https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded;onload=myRecaptchaApiLoaded&render=explicit"`

`onload=vueRecaptchaApiLoaded&onload=myRecaptchaApiLoaded`

(Just kidding,This cannot be achieved)

The problem of slow js loading is difficult to solve, so I hope to give users a good wait reminder.

**Comment by DanSnow** [comment]
Here's a workaround:

1.  change the `onload` param in recaptcha url to `myRecaptchaApiLoaded`

2.

```js
window.myRecaptchaApiLoaded = () => {
  // remember to notify `vue-recaptcha`
  vueRecaptchaApiLoaded()
  // your logic
}
```
