### ISSUE TITLE
size=invisible doesn't invoke @verify

### ISSUE THREAD

**Issue by supasonk** [DanSnow/vue-recaptcha#333]

**Comment by max8hine** [comment]
My issue is the `verify` event doesn't always invoke but on the first time of the form submission.

Is the `reset` action need to be called on the end of a form submission or verify event?

Based on [the current example](https://github.com/DanSnow/vue-recaptcha/blob/master/example/main.js), running the `this.$refs.invisibleRecaptcha.execute()` in between the form submission seems is preventing form submission if Recaptcha reckon it is a bot action. I felt I've been misleading there.

Wish there are some of the best practices in the doc or an example to show how to submit a form with this lib.

**Comment by DanSnow** [comment]
When you pass the recpatcha test (`verify` event fired), you'll get a token.  Before the token expired, calling `execute()` will not trigger the recaptcha test again. So if you want to trigger the test again, I'll recommend you call `reset` before calling `execute`.

**Comment by max8hine** [comment]
Thanks @DanSnow for taking your time and answering here.

Do you know how to trigger the invisible Recaptcha with the puzzles UI on for testing?

I've tried to set the user agent to Googlebot in Chrome as below screenshot but I am still able to pass the Recaptcha verification.

![image](https://user-images.githubusercontent.com/15165714/78615442-a9bf5300-78c5-11ea-8c57-a57b0bb166b7.png)

**Comment by SerhiyRomanov** [comment]
@DanSnow 

> When you pass the recpatcha test (verify event fired), you'll get a token. Before the token expired, calling execute() will not trigger the recaptcha test again. So if you want to trigger the test again, I'll recommend you call reset before calling execute.

I would like to see this explanation in docs instead of searching it among issues. Btw, thank you for a good job, component works perfectly!
