### ISSUE TITLE
Recaptcha bypasses

### ISSUE THREAD

**Issue by dlenskyi** [DanSnow/vue-recaptcha#334]
Recaptcha-v3 not working at all, it says invalid site key, but I created a fresh keys.
Invisible recaptcha-v2 started to work, but `this.$refs.recaptcha.execute()` doesn't show the recaptcha, it bypasses and goes to `@verify` method, my browser is Safari. In Google Chrome it does the same

**Comment by DanSnow** [comment]
invisible recaptcha will pass directly if Google thinks that you are human

**Comment by dlenskyi** [comment]
Thanks, all worked!
