### ISSUE TITLE
invisible reCaptcha?

### ISSUE THREAD

**Issue by delueg** [DanSnow/vue-recaptcha#39]
Hello ,

is the invisble reCaptcha available?

https://developers.google.com/recaptcha/docs/invisible

**Comment by DanSnow** [comment]
Currently, no.
But this is a planning feature.

**Comment by DanSnow** [comment]
I have implemented an experimental version at current HEAD.
You can bind the ReCAPTCHA to a button like this:
```html
<vue-recaptcha sitekey="<sitekey>">
  <button type="submit">Submit</button>
</vue-recaptcha>
```
**But** it can only support html tags.
You can't use any Vue component.

**Comment by DanSnow** [comment]
I have published a new version. Check it out.
