### ISSUE TITLE
vue with typescript, how to validation

### ISSUE THREAD

**Issue by EwaMakowska** [DanSnow/vue-recaptcha#447]
I don't know how to use execute method and verify my form. Property 'execute' does not exist on type MyComponent. 

my component is really simply:

```
<template>
  <div class="row q-mb-lg">
    <vue-recaptcha :sitekey="siteKey" :loadRecaptchaScript="true" size="invisible">
    </vue-recaptcha>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Emit } from 'vue-property-decorator'

import VueRecaptcha from 'vue-recaptcha'

@Component({
  components: {
    VueRecaptcha 
  }
})
export default class ReCAPTCHComponent extends Vue {
  private siteKey: string = '####'

}
```

but I don't know how to use execute, verify. I have to connect it with my submit form?

**Comment by DanSnow** [comment]
Sorry for the late reply.

You can declare the `$refs` in your component:

```ts
@Component({ ... })
class ReCAPTCHComponent extends Vue {
  $refs!: {
    recaptcha: VueRecaptcha,
  }
}
```

or just cast it when you are trying to access the ref:

```ts
@Component({ ... })
class ReCAPTCHComponent extends Vue {
  handleSubmit() {
    const recaptcha = this.$refs.recaptcha as VueRecaptcha
    // now you can call `execute`
    recaptcha.execute()
  }
}
```

For more information, please reference this stackoverflow answer
https://stackoverflow.com/questions/46505813/vuejs-typescript-this-refs-reffield-value-does-not-exist
