### ISSUE TITLE
IE11 issues recaptcha in Vue

### ISSUE THREAD

**Issue by trialsNow** [DanSnow/vue-recaptcha#458]
I use vue-recaptcha in my application. It works in all other browsers except IE11

It fails in index.html where i have this script
	<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit" async defer>
	</script>

The sad part when initially loaded in my local it works good then if i refresh or server not restarted i start getting this eror
HTML1300: Navigation occurred.
555776
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
555776
SCRIPT5022: Exception thrown and not caught
chunk-vendors.efabc419.js (43,8345)
SCRIPT5005: String expected
recaptcha__en.js (81,183)

![image](https://user-images.githubusercontent.com/16502814/86279934-7d536400-bba0-11ea-81bb-978e7df0efb9.png)

Any help sooner is greatly appreciated? The same recaptcha src if i use in JSP I have absolutely no issues

**Comment by efesezer** [comment]
I have same issue. Does anybody have any comment? It would be perfect if you have

**Comment by trialsNow** [comment]
@efesezer If its on any help.. this issue got fixed when i removed the script src for google recaptcha from index.html and used loadRecaptchaScript=true in vue-recaptcha

**Comment by efesezer** [comment]
I have made your suggestion but error message has been changed to "Accessing the 'caller' property of a function or arguments object is not allowed in strict mode".

Do you have any idea what I should do?
![image](https://user-images.githubusercontent.com/3841938/88048567-38e23500-cb5c-11ea-9478-e1a0d01e1f6b.png)
