### ISSUE TITLE
IE - String Expected Error

### ISSUE THREAD

**Issue by efesezer** [DanSnow/vue-recaptcha#472]
I use vue-recaptcha for my application. It works in all other browsers except IE11

![image](https://user-images.githubusercontent.com/3841938/87936262-32d84f80-ca9b-11ea-9ac0-e2c0f32d6440.png)

I have error message like above picture.

SCRIPT5005: String expected
recaptcha__tr.js (73,351)
SCRIPT5005: String expected
recaptcha__tr.js (260,211)

Does anyone have any comment on that issue?

**Comment by DanSnow** [comment]
This is the problem with ReCAPTCHA's widget. I could not provide any help. It's better to report this to [google/recaptcha](https://github.com/google/recaptcha) or ask this question on Stackoverflow.
