### ISSUE TITLE
Make a proper npm release

### ISSUE THREAD

**Issue by alfhen** [DanSnow/vue-recaptcha#5]
Hey could you make a proper release on npm so we don't have to write:
``` javascript
npm install git+https://github.com/DanSnow/vue-recaptcha.git
```
but will be able to write:
``` javascript
npm install vue-recapthca
```

**Comment by DanSnow** [comment]
OK. I will release it recently.

BTW. I released this package exactly when "left-pad" occurred. 
So I didn't plan to release this package on npm at that duration.

**Comment by DanSnow** [comment]
I have released on npm. [https://www.npmjs.com/package/vue-recaptcha](https://www.npmjs.com/package/vue-recaptcha)

**Comment by alfhen** [comment]
Cool thanks 👍
