### ISSUE TITLE
Uncaught Error: ReCAPTCHA has not been loaded

### ISSUE THREAD

**Issue by arunrreddy** [DanSnow/vue-recaptcha#50]
This happens when I reload the page. It is working fine on the first to the page but when the page is reloaded I get this error. Also, there is no implementation of the 'vueRecaptchaApiLoaded' function which is supposed to be triggered on the load of the recaptcha from google. Please look into this.

**Comment by DanSnow** [comment]
Thanks for reporting issue.
Please provide a gist that can reproduce this issue.

This error will happen when you are trying to access reCAPTCHA's function like `reset` or `execute`
before reCAPTCHA completely loaded.
Actually, this shouldn't happen in mostly case.
And I don't understand what is "no implementation of the 'vueRecaptchaApiLoaded' function" mean?

**Comment by arunrreddy** [comment]
I figured it out. It was my mistake.
