### ISSUE TITLE
working with cors and other warnings

### ISSUE THREAD

**Issue by greenpdx** [DanSnow/vue-recaptcha#527]
I am getting many warnings but where I fails in with cors.

Uncaught DOMException: Permission denied to access property "dispatchEvent" on cross-origin object.

Setup:
index.html added
```
 <script src="https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit" async defer>
  </script>
```

in component template:
```
<vue-recaptcha sitekey="XXX"
              ref="recaptcha"
              @verify="onCaptVerify"
              @expired="onCaptExpire">
            </vue-recaptcha>
```
in component script:
```
import VueRecaptcha from 'vue-recaptcha';
//const recaptSiteKey = 'XXX'

// Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character:
const MODAL_WIDTH = 656

export default {
  name: 'LoginModal',
  components: {
    VueRecaptcha
  },
```
I want the captcha to show.

Here are all the warnings I get.
1>  GEThttps://10.0.42.19:8080/js/app.js
Cookie “SIDCC” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

2> GEThttps://www.google.com/recaptcha/api2/anchor?ar=1&k=
 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
13:09:56.009 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
13:09:56.009 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
13:09:56.015 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
13:09:56.015 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
13:09:56.015 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

**Comment by DanSnow** [comment]
`vue-recaptcha` itself doesn't access any resource directly. So it's impossible to produce such message.

And I could not found any related issue between Google reCAPTCHA and the message you post. So I guess that it may not relate to `vue-recaotcha` or Google reCAPTCHA. Also, the messages you post show that you are using CSP. You can check out the CSP config for the reCAPTCHA at [here](https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha).

**Comment by Ksardarion** [comment]
@DanSnow 
You'll get such errors in case of using the iPhone with Safari:
_The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored._

**Comment by elsiosanchez** [comment]
I recommend that you read this could solve your problem
https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha

**Comment by greenpdx** [comment]
Thanks, that has given somewhere to start
