### ISSUE TITLE
the language prop not work

### ISSUE THREAD

**Issue by eliyahuKriel** [DanSnow/vue-recaptcha#538]
hi guys , thanks fro this great plugin

the `language` not work, its not effect on the recptcha wigidt

ah this image you can see the the chalenge is in english (default), buy the selected lang by props  is 'ih' -> Hindi

![image](https://user-images.githubusercontent.com/59528365/95673363-674a3c00-0bb0-11eb-9ff5-92d615458625.png)

the code look like this

     
        <vue-recaptcha
                    language="hi"
                    @verify="submit"
                    ref="invisibleRecaptcha"
                    :sitekey="$store.state.appMetaData.siteKey"
                    size="invisible">
            </vue-recaptcha>

**Comment by DanSnow** [comment]
It only work if you also set `loadRecaptchaScript` to `true`

**Comment by eliyahuKriel** [comment]
thanks
i have another problem, after i success to login and send the recptcha token - i see this error msg in the console:

`recaptcha__iw.js:725 Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at Ox.gG.sJ (https://www.gstatic.com/recaptcha/releases/48TunWH-ZrLteSwFVbw6tVnx/recaptcha__iw.js:725:102)
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/48TunWH-ZrLteSwFVbw6tVnx/recaptcha__iw.js:80:138)
    at Object.init (https://www.gstatic.com/recaptcha/releases/48TunWH-ZrLteSwFVbw6tVnx/recaptcha__iw.js:731:44)
    at https://www.google.com/recaptcha/api2/bframe?hl=iw&v=48TunWH-ZrLteSwFVbw6tVnx&k=6LfstrcZAAAAAFCNNklv2Cnqm4-m4pxbKiFBdvmi&cb=yra6moza6i2m:184:30`

**Comment by misaghkarimi** [comment]
what is said here didn't work for me and language didn't change
```
language="fa"
:loadRecaptchaScript="true"
```
 
instead this method worked fine and I got recaotcha in my desire language
putting this script in index.html head with parameter &hl=fa  at the end and also :loadRecaptchaScript="true" must be removed from the template

```
    <script src="https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit&hl=fa" async defer>
    </script>
```
