### ISSUE TITLE
Captcha doesn't render

### ISSUE THREAD

**Issue by ghost** [DanSnow/vue-recaptcha#554]
`Uncaught TypeError: h is not a function
    render vue-recaptcha.es.js:198
    renderComponentRoot runtime-core.esm-bundler.js:681
    componentEffect runtime-core.esm-bundler.js:4018
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4001
    mountComponent runtime-core.esm-bundler.js:3959
    processComponent runtime-core.esm-bundler.js:3919
    patch runtime-core.esm-bundler.js:3531
    mountChildren runtime-core.esm-bundler.js:3720
    mountElement runtime-core.esm-bundler.js:3643
    processElement runtime-core.esm-bundler.js:3615
    patch runtime-core.esm-bundler.js:3528
    mountChildren runtime-core.esm-bundler.js:3720
    mountElement runtime-core.esm-bundler.js:3643
    processElement runtime-core.esm-bundler.js:3615
    patch runtime-core.esm-bundler.js:3528
    componentEffect runtime-core.esm-bundler.js:4036
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4001
    mountComponent runtime-core.esm-bundler.js:3959
    processComponent runtime-core.esm-bundler.js:3919
    patch runtime-core.esm-bundler.js:3531
    mountChildren runtime-core.esm-bundler.js:3720
    mountElement runtime-core.esm-bundler.js:3643
    processElement runtime-core.esm-bundler.js:3615
    patch runtime-core.esm-bundler.js:3528
    componentEffect runtime-core.esm-bundler.js:4036
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4001
    mountComponent runtime-core.esm-bundler.js:3959
    processComponent runtime-core.esm-bundler.js:3919
    patch runtime-core.esm-bundler.js:3531
    render runtime-core.esm-bundler.js:4614
    mount runtime-core.esm-bundler.js:2969
    mount runtime-dom.esm-bundler.js:1208
    <anonymous> main.ts:6
    ts app.js:1069
    __webpack_require__ app.js:849
    fn app.js:151
    1 app.js:1106
    __webpack_require__ app.js:849
    checkDeferredModules app.js:46
    <anonymous> app.js:925
    <anonymous> app.js:928
vue-recaptcha.es.js:198
`

**Comment by DanSnow** [comment]
The supporting for vue 3 hasn't released yet.

**Comment by realchandan** [comment]
Ohh, It did work in my other projects made in Vue 2, now I get It why!
Thanks for letting making it clear!
