### ISSUE TITLE
Property or method 'onError'...'onSuccess'...'onExpired' ...errors in console

### ISSUE THREAD

**Issue by c-myers1** [DanSnow/vue-recaptcha#555]
I've incorporated vue-recaptcha in my nuxt app and it seems to be working (at least the front-end bits of dispaying the images and then ticking when correctly selected) but it gives a lot of errors in the browser console (image attached.)

Now when I comment out vue-recaptcha in the modules section of nuxt.config.js and also in the template, my site displays without any errors. So I know it has something to do with the library. How do I fix it? I'm worried it might cause issues with something else not yet known.

![image](https://user-images.githubusercontent.com/42839510/97781501-28dee600-1b8c-11eb-8601-864813bd0c92.png)

**Comment by DanSnow** [comment]
Did you just copy & paste the example code? You'll need to create and define your logic in those methods.

**Comment by c-myers1** [comment]
Not sure what I did, but these errors stopped. Thanks
