### ISSUE TITLE
Send captcha through Axios - Laravel Mix

### ISSUE THREAD

**Issue by felloz** [DanSnow/vue-recaptcha#556]
Hello,

I'm trying to using your vue lib but,  I need to send the captcha to backend, I'm using `axios` to do that. But Idk how to get the info from the component `<vue-recaptcha>` to an attribute in `data` to send it in the `axios.post`

This is not an issue, its only something that I need to do and dont find a useful info on internet. I'm using Laravel Mix + Vue.

Thank you.

An example of my code:

```
<template>
  <form @submit="register">
  <input type="text" name="anyname">
  <vue-recaptcha sitekey="Your key here" :loadRecaptchaScript="true"></vue-recaptcha>
  <input type="submit" value="Enviar">
  </form>
</template>

<script>
  import VueRecaptcha from 'vue-recaptcha';
  export default {
    ...
    components: {
      VueRecaptcha
    },
    methods: {
      register() {
        axios
          .post("/contact", {
            name: this.name,
            email: this.email,
            phone: this.phone,
            body: this.body,
          })
          .then(response =>
            this.responseMessage(
              response.data.code,
              response.data.response
            )
          )
          .catch(err => console.log(err));
      }

    }
  };
</script>
```

**Comment by Zajozor** [comment]
random other user here. this is pretty high in search results for me, so here is a bit of advice.

We are using axios successfully with this project.

```
 <vue-recaptcha
    ref="googleRecaptcha"
    :load-recaptcha-script="true"
    :sitekey="recaptchaSitekey"
    @verify="register"
  >
    <input      
      type="submit"
    >
      Register
    </input>
  </vue-recaptcha>
```

you can use the input inside the recaptcha component and then use the @verify event to run the registration/submit of the form. The register method should have a single parameter, which will contain the recaptcha value.
