### ISSUE TITLE
invisible + popup issues

### ISSUE THREAD

**Issue by robertnicjoo** [DanSnow/vue-recaptcha#569]
It seems like this package doesn't work in general.

```javascript
<vue-recaptcha
            sitekey="......."
            size="invisible"
            :loadRecaptchaScript="true"
          >
            <vs-button @click="onSubmit" native-type="submit" gradient>
              {{ $t("contacts.send") }}
            </vs-button>
</vue-recaptcha>
```

### Issues

1. `size="invisible"` still can see badge.
2. Popup never shows up.

**Extra question**

Don't we need to provide `secret key` at all?!

**Comment by DanSnow** [comment]
1. You can hide the badge by yourself if you follow the requirement at [here](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed)
2. Please handle the form submit in the `@verify` callback
3. No!!! The secret key is using for verifying the recaptcha response and you should not leak it.

**Comment by robertnicjoo** [comment]
@DanSnow Thanks for the response. I've changed my code like:

```javascript
<vue-recaptcha
  ref="invisibleRecaptcha"
  @verify="onVerify"
  @expired="onExpired"
  size="invisible"
  :sitekey="sitekey"
  :loadRecaptchaScript="true"
>
  <vs-button @click="onSubmit" native-type="submit" gradient>
    {{ $t("contacts.send") }}
  </vs-button>
</vue-recaptcha>
```

### Solved

1. hidden badge is fixed now.
2. `secret key` understood.

### Remained issues

1. I don't get any popup yet.
2. How do I keep my submit progress until I get `@verify` response?

`PS` in console I get token key from google which I assume means it was successful. but how do I implement issue number 2 in it?


```javascript

components: { VueRecaptcha },
  methods: {
    onVerify: function (response) { // newly added
      console.log("Verify: " + response);
    },
    onExpired: function () { // newly added
      console.log("Expired");
    },
    onSubmit(e) {
      e.preventDefault();
      this.$refs.invisibleRecaptcha.execute(); // newly added
      // axios.....
   }
```

**Comment by DanSnow** [comment]
1. If Google think that you are human, then you won't get a popup. Just make sure that you can get the verify response.
2. You can try these steps:
  1. just trigger recaptcha and prevent the default action in the `@click`
  2. move the `axios` call to `@verify`

**Comment by robertnicjoo** [comment]
@DanSnow  thank you so much

`Final code for those in need`

```html
<form
          ref="form"
          @submit.prevent="onSubmit" // <-- here
          :model="form"
          enctype="multipart/form-data"
>
        <vue-recaptcha
            ref="invisibleRecaptcha"
            @verify="onSubmit" // <-- here
            @expired="onExpired"
            size="invisible"
            :sitekey="sitekey"
            :loadRecaptchaScript="true"
          >
            <vs-button native-type="submit" gradient>
              {{ $t("contacts.send") }}
            </vs-button>
          </vue-recaptcha>
</form>
```

```javascript
methods: {
    onExpired: function () {
      console.log("Expired");
    },
    onSubmit(e) {
      console.log("Verify: " + e); // <-- test captcha response
      this.$refs.invisibleRecaptcha.execute(); // < -- here
      axios.... // <-- send request
```
