### ISSUE TITLE
Reset vue recaptcha

### ISSUE THREAD

**Issue by liyou44** [DanSnow/vue-recaptcha#6]
Hi,

I have a question, how do you reset vue recaptcha?

**Comment by DanSnow** [comment]
You can use v-ref to get the instance and call reset method on it.
Or broadcast "recaptchaReset" event.
I have added an example of this. Please reference it.
[https://github.com/DanSnow/vue-recaptcha/blob/master/example/main.js#L20-L21](https://github.com/DanSnow/vue-recaptcha/blob/master/example/main.js#L20-L21)

**Comment by liyou44** [comment]
Thanks, it's working now
