### ISSUE TITLE
Issue with User provider function

### ISSUE THREAD

**Issue by stevepop** [DanSnow/vue-recaptcha#60]
When my signup page implementing vue-recaptcha is loaded, I keep seeing this message in my console;
```
ReCAPTCHA couldn't find user-provided function: vueRecaptchaApiLoaded
```
Seems to be referenced from https://www.gstatic.com/recaptcha/api2/r20170524165316/recaptcha__en.js
I don't know why this is happening as I can see from vue-recaptcha code that the method `vueRecaptchaApiLoaded` is attached to the window object.
I am using this with npm/webpack.

Thanks!

**Comment by DanSnow** [comment]
Well. It's fine.
It mean reCAPTCHA is loaded before your app.
vue-recaptcha still can detect and load reCAPTCHA.

If you really care about it, you can try to move reCAPTCHA api before body's end tag.

**Comment by stevepop** [comment]
Thanks for your quick response @DanSnow.
