### ISSUE TITLE
Cant seem to get this to work.

### ISSUE THREAD

**Issue by timothymarois** [DanSnow/vue-recaptcha#608]
ive tried many options here, and cant seem to get this to work.

1) Installed package
2) Added to vue template (imported) as seen in readme
3) Added googles js in header
4) Added site key

```
 Error: No reCAPTCHA clients exist.
```

Failed on input button (it did nothing at all), so moved to force the event, 
After trying to invoke the event: `window.grecaptcha.execute();` 

Edit: found the other example:

And realized you can run `this.$refs.invisibleRecaptcha.execute();` But then there also doesn't exist.

To clarify on my setup, I'm using VueJs, VuetifyJS and NuxtJS. For me, `this.$refs` is empty.

**Comment by DanSnow** [comment]
Could you try with `loadRecaptchaScript` ([doc](https://github.com/DanSnow/vue-recaptcha#auto-load-script)) ?

**Comment by DanSnow** [comment]
Close as inactive
