### ISSUE TITLE
Error when try to bind validate on click at div (not at button)

### ISSUE THREAD

**Issue by alexdpts** [DanSnow/vue-recaptcha#619]
recaptcha__ru.js:325 Uncaught (in promise) Error: reCAPTCHA placeholder element must be empty
    at recaptcha__ru.js:325
    at Array.<anonymous> (vue-recaptcha.min.js:1)
    at Object.resolve (vue-recaptcha.min.js:1)
    at notify (vue-recaptcha.min.js:1)

I try to bind it on click at div because i need to enable/disable element (button) depends on form validation, but vue-recaptcha is cutting ':disabled="isButtonDisabled"' at start on button element.

**Comment by DanSnow** [comment]
Please try to manual trigger it as `vue-recaptcha` doesn't support disable
