### ISSUE TITLE
update dependency husky to v7.0.1 in the branch vue-v3

### ISSUE THREAD

**Issue by rust97** [DanSnow/vue-recaptcha#650]
please update the dependency in the branch vue-v3

**Comment by neklein** [comment]
With husky v7.0.0, it looks like there is a `.git can't be found error. Definitely need v7.0.01

**Comment by neklein** [comment]
Seems like the problem is addressed here: https://github.com/typicode/husky/issues/1003

Not sure if `prepare` is needed as well.

**Comment by DanSnow** [comment]
Fix by #651
