### ISSUE TITLE
No method for 'expired' scenario

### ISSUE THREAD

**Issue by nwrightau** [DanSnow/vue-recaptcha#66]
After the user checks the box and solves the captcha, if a period of time passes recaptcha will invalidate it and ask them to solve it again, but I'm not seeing a way for that to be reflected in Vue. If there isn't a method available, there probably should be.

Would appreciate your thoughts on this.

**Comment by DanSnow** [comment]
Actually there is a "expired" event.
Sorry. I miss the document for it.

Usage:
```html
<vue-recaptcha @verify="onVerify" @expired="onExpired"></vue-recaptcha>
```

**Comment by nwrightau** [comment]
Excellent, works perfect - definitely add that to the docs 😄
