### ISSUE TITLE
IE error

### ISSUE THREAD

**Issue by MBakirci** [DanSnow/vue-recaptcha#7]
Hi,

I got an error in Internet Explorer(all versions).
Error "SCRIPT438: Object doesn't support property or method 'call' "

When i disable the plugin the page is loading other wise it redirect me to '/ '

**Comment by DanSnow** [comment]
I have tested in IE 11. But I didn't get any problem.
Please make sure you have loaded any es6 polyfill for IE.
This library depend on `Promise` and `Object.assign`, so you must have these polyfill at least.

If you still get the same error, please provide a code snippet containing a set of reproducible steps.

**Comment by MBakirci** [comment]
I'm using this package for some polyfill stuff:
https://github.com/stefanpenner/es6-promise

Do I need another package for something else?

**Comment by DanSnow** [comment]
You will need https://github.com/es-shims/es6-shim for `Object.assign`.
Or any polyfill that includes `Object.assign`.
