### ISSUE TITLE
New version not working with Vue2

### ISSUE THREAD

**Issue by DaveInTO** [DanSnow/vue-recaptcha#740]
Continue to receive this.
I've included the libs you list in the docs.
TypeError: this.$refs.recaptcha.execute is not a function

Is the old version of the code available somewhere?

**Comment by gm9510** [comment]
<script src="https://unpkg.com/vue-recaptcha@^1/dist/vue-recaptcha.min.js"></script>

Using de 1.3.0 version, it works again.

**Comment by Esurnir** [comment]
In my case I'm getting : 
`Error in render: "TypeError: _this$$slots$default.call is not a function"`
It seems sometimes this.$slots.default is an array of a single VNode, because why make things simple.
