### ISSUE TITLE
dependency was not found:

### ISSUE THREAD

**Issue by yh17838** [DanSnow/vue-recaptcha#754]
vue2.0 

This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs

To install it, you can run: npm install --save @vue/composition-api/dist/vue-composition-api.mjs

**Comment by alisson446** [comment]
I'm with same problem installing in the quasar version 1.0.0 :(

**Comment by YusufcanY** [comment]
same problem on "nuxt": "^2.0.0",

**Comment by lmx01** [comment]
same problem in Vue2.0

**Comment by lmx01** [comment]
Does anyone  fix this problem?Thanks.

**Comment by PamelaPz** [comment]
Same problem in Vue 2.6.11

This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs

**Comment by juliojmjc** [comment]
just install @vue/composition-api

**Comment by maelquerre** [comment]
It is indeed a breaking change of the [v2.0.0](https://github.com/DanSnow/vue-recaptcha/releases/tag/v2.0.0)

> You will need to install [@vue/composition-api](https://github.com/vuejs/composition-api) if you want to use this package with Vue 2
