### ISSUE TITLE
validation server side

### ISSUE THREAD

**Issue by mrwahyurpakoso** [DanSnow/vue-recaptcha#77]
how to validate recaptcha in server side?

**Comment by DanSnow** [comment]
vue-recaptcha is just a wrapper for reCAPTCHA at client side.
It's not care about how you to validate reCAPTCHA's response.
So, I'll close this issue.

And for your question, it's relating to your language,
Mostly, you can found a package for your language or framework.
For example, here is one for Laravel.
https://github.com/greggilbert/recaptcha
Just use "[your language or framework] recaptcha" as keyword to search it.

If you still have problem, I think [stackoverflow](https://stackoverflow.com) will be a better place for this question. :+1:

**Comment by PhPPgAdminBug** [comment]
That package can not be use with Vue. But it is perfect for Laravel view blades.

**Comment by DanSnow** [comment]
@PhPPgAdminBug Thanks for comment.
But I think maybe we can just use its validation rule.
Actually, I'm not sure. Since I'm not familiar with Laravel.
