### ISSUE TITLE
vueDemi.defineComponent is not a function Error Not working with Nuxt 3

### ISSUE THREAD

**Issue by anish2690** [DanSnow/vue-recaptcha#808]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/22445409/165269735-d9c0e0f7-1c1f-49f5-9e4e-6289efdb9a1a.png">

**Comment by DanSnow** [comment]
I have not tried Nuxt 3. Is it possible to make it client-only?

**Comment by IlyaSemenov** [comment]
It's also crashing the same way on nuxt/bridge (vue2) in vite/nitro mode.

**Comment by alehano** [comment]
I got this to work.
Under `/plugins` dir create a file named `recaptcha.client.js` with contents:
```js
import { VueRecaptcha } from 'vue-recaptcha';

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.component('VueRecaptcha', VueRecaptcha)
})
```
Then you can use `<VueRecaptcha>` wrapped with `<ClientOnly>` in your components

**Comment by zhixXiang** [comment]
> I got this to work. Under `/plugins` dir create a file named `recaptcha.client.js` with contents:
> 
> ```js
> import { VueRecaptcha } from 'vue-recaptcha';
> 
> export default defineNuxtPlugin(nuxtApp => {
>     nuxtApp.vueApp.component('VueRecaptcha', VueRecaptcha)
> })
> ```
> 
> Then you can use `<VueRecaptcha>` wrapped with `<ClientOnly>` in your components

Thank you, you save my day!

**Comment by matrixmandeep** [comment]
Hey, can you please share an example to implement this on nuxt 3
