### ISSUE TITLE
Issue when importing the component

### ISSUE THREAD

**Issue by jxli888** [DanSnow/vue-recaptcha#825]
Thanks for the component!  we are using Vuejs 2.6.  The issue we found is that when importing the vue-recaptcha component.  We need to do something like this, **note the curly brackets**, otherwise, it complains the component is not found. 

**import {VueCaptcha} from 'vue-recaptcha'**

**Comment by ksrigangadhar** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'defineComponent')

![image](https://user-images.githubusercontent.com/62547172/170654762-e1a4bd8b-5b06-499a-bfbd-1d831e9a5f3b.png)
![image](https://user-images.githubusercontent.com/62547172/170654904-fdc2d40f-6253-4a79-be64-c0413728f772.png)
![image](https://user-images.githubusercontent.com/62547172/170655076-096aeaa8-b0ad-4bde-ad9c-965dcc3c00b4.png)
![image](https://user-images.githubusercontent.com/62547172/170655331-9a13965f-5e1e-433b-a8b6-886e6ead18db.png)

**Comment by DanSnow** [comment]
duplicate with #754
