### ISSUE TITLE
vue-recaptcha must be in your package.json?

### ISSUE THREAD

**Issue by PhPPgAdminBug** [DanSnow/vue-recaptcha#86]
Installed with commands from tutorial, but there is no package added to package.json.
So we use 
` "vue-recaptcha": "*",`
end this works fine.

But not sure it is right. **maybe we should add version? How to know which one?** 

Also, Git link are broken from your docs. 

> For more information, please reference to ReCAPTCHA document and Invisible ReCAPTCHA document.

**Comment by DanSnow** [comment]
Sorry, my fault.
Please use `npm install --save vue-recaptcha` or `yarn add vue-recaptcha`.
Also, I fixed the links.
