### ISSUE TITLE
This site key is not enabled for the invisible captcha

### ISSUE THREAD

**Issue by iamdubx** [DanSnow/vue-recaptcha#87]
Hello. I did everything from code snippets in Docs, but when the page load I got this message from Google

```
This site key is not enabled for the invisible captcha
```

I don't want invisible in first place. 
Ho to make it V2?

**Comment by DanSnow** [comment]
Please don't put anything inside `vue-recaptcha`. Or it will try to attach an invisible captcha on child.
If you still have the issue, please post your code snippet.

**Comment by iamdubx** [comment]
Thanks, I fixed it.
