### ISSUE TITLE
How to use the "size" prop

### ISSUE THREAD

**Issue by Atif-Bashir-1998** [DanSnow/vue-recaptcha#894]
I am using Vue 3 with Tailwind CSS. I tried to add general values for size (i.e full, 300px, max etc) but nothing happened. So how to use the size prop?

Link to [documentation](https://www.npmjs.com/package/vue-recaptcha#props:~:text=type%20of%20reCAPTCHA-,size,-(optional)%20%E2%80%93%20The%20size).

**Comment by neonanal** [comment]
Slightly counter-intuitive, but in captcha's case `size` is either `invisible` (invisible captcha) or `null` (= normal captcha), nothing to do with widget size. I guess `type` attribute was supposed to bear this functionality, but something went wrong...

**Comment by dotJoel** [comment]
Currently, the `size` property can also be `compact` or its default `normal`.
https://developers.google.com/recaptcha/docs/display#render_param

This package seems to just pass down any props to the `grecaptcha.render()`.

This information doesn't really help with the original question about custom width, but seemed relevant.

**Comment by DanSnow** [comment]
Yes, vue-recaptcha only pass the `size` to `grecaptcha.render()`. The reCAPTCHA style is not changeable by vue-recaptcha.
